os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - lcov
    - astyle
    - devscripts
    - python
    - python-pip
    - python-autopep8
    - doxygen
    - fakeroot
    - debhelper
    - pkg-config
    - alien
    - rpm
    - dh-make
    - dh-golang
install:
  - gem install coveralls-lcov

matrix:
  include:
    - language: c
      script:
        - make c
      after_success:
        - coveralls-lcov /home/travis/build/Genomicsplc/variantkey/c/target/test/coverage/variantkey.info
    - language: go
      script:
        - make go
    - language: python
      script:
        - make python
    - language: r
      script:
        - make r
    - language: node_js
      node_js:
        - "7"
      install:
        - npm install --global uglify-js js-beautify
      script:
        - make javascript
      
